# Generated by Django 3.2.6 on 2021-08-24 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appneos', '0002_auto_20210824_1459'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avaliacao',
        ),
        migrations.DeleteModel(
            name='ClientesCliente',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Contato',
        ),
        migrations.DeleteModel(
            name='Denuncia',
        ),
        migrations.DeleteModel(
            name='Local',
        ),
        migrations.DeleteModel(
            name='Notificacoes',
        ),
    ]
